import JSZip from 'jszip'
import type { AuditResult } from '@auditkit/collectors'
import {
    generateAgentsMd,
    generateClaudeMd,
    generateGeminiMd,
    generateSkillMd,
    generateRobotsTxt,
    generateSecurityHeaders,
    generateLlmsTxt,
} from './templates.js'

export { generateAgentsMd, generateClaudeMd, generateGeminiMd, generateSkillMd } from './templates.js'

export async function generateBriefZip(result: AuditResult): Promise<Blob> {
    const zip = new JSZip()
    const domain = new URL(result.url).hostname.replace('www.', '')
    const root = zip.folder(`auditkit-brief-${domain}`)!

    // Core AI brief files
    root.file('AGENTS.md', generateAgentsMd(result))
    root.file('CLAUDE.md', generateClaudeMd(result))
    root.file('GEMINI.md', generateGeminiMd(result))
    root.file('llms.txt', generateLlmsTxt(result))

    // Per-pillar skill files
    const skills = root.folder('.agents/skills')!
    for (const pillar of result.pillars) {
        if (pillar.issues.length === 0) continue
        const skillDir = skills.folder(pillar.id)!
        skillDir.file(
            'SKILL.md',
            generateSkillMd(pillar.label, pillar.issues, result.url),
        )
    }

    // Checklists
    const checklists = root.folder('checklists')!
    for (const pillar of result.pillars) {
        if (pillar.issues.length === 0) continue
        const checklist = [
            `# ${pillar.label} Checklist\n`,
            `> Score: ${pillar.score}/100\n`,
            ...pillar.issues.map(
                (i) => `- [ ] **${i.title}** (${i.severity})${i.fix ? ` — ${i.fix}` : ''}`,
            ),
        ].join('\n')
        checklists.file(`${pillar.id}.md`, checklist)
    }

    // Ready-to-deploy configs
    const deploy = root.folder('ready-to-deploy')!
    deploy.file('robots.txt', generateRobotsTxt(result.url))
    deploy.file('security-headers.next.js', generateSecurityHeaders())

    // Structured data example if missing
    const sdPillar = result.pillars.find((p) => p.id === 'structured-data')
    if (sdPillar && sdPillar.score < 70) {
        deploy.file(
            'structured-data.jsonld',
            JSON.stringify(
                {
                    '@context': 'https://schema.org',
                    '@type': 'WebSite',
                    name: result.meta?.title ?? domain,
                    url: result.url,
                    description: result.meta?.description ?? '',
                },
                null,
                2,
            ),
        )
    }

    // Dependabot config if missing (GitHub audits)
    if (result.type === 'github') {
        const github = root.folder('.github')!
        github.file(
            'dependabot.yml',
            [
                '# Dependabot config — generated by AuditKit',
                'version: 2',
                'updates:',
                '  - package-ecosystem: npm',
                '    directory: "/"',
                '    schedule:',
                '      interval: weekly',
                '    open-pull-requests-limit: 5',
            ].join('\n'),
        )
    }

    // Audit summary JSON
    root.file(
        'audit-summary.json',
        JSON.stringify(
            {
                url: result.url,
                type: result.type,
                auditedAt: result.auditedAt,
                scores: Object.fromEntries(result.pillars.map((p) => [p.id, p.score])),
                totalIssues: result.pillars.flatMap((p) => p.issues).length,
                criticalIssues: result.pillars
                    .flatMap((p) => p.issues)
                    .filter((i) => i.severity === 'critical').length,
            },
            null,
            2,
        ),
    )

    return zip.generateAsync({ type: 'blob' })
}
