import type { AuditResult, AuditIssue } from '@auditkit/collectors'

// ─── AGENTS.md ────────────────────────────────────────────────────────────────

export function generateAgentsMd(result: AuditResult): string {
    const date = new Date(result.auditedAt).toLocaleDateString('en-US', {
        year: 'numeric', month: 'long', day: 'numeric',
    })
    const allIssues = result.pillars.flatMap((p) => p.issues)
    const critical = allIssues.filter((i) => i.severity === 'critical')
    const warnings = allIssues.filter((i) => i.severity === 'warning')

    const issueList = (issues: AuditIssue[]) =>
        issues.map((i) => `- **${i.title}**: ${i.description}${i.fix ? `\n  - Fix: ${i.fix}` : ''}`).join('\n')

    const pillarSummary = result.pillars
        .map((p) => `| ${p.label} | ${p.score}/100 | ${p.issues.filter((i) => i.severity === 'critical').length} critical, ${p.issues.filter((i) => i.severity === 'warning').length} warnings |`)
        .join('\n')

    return `# AGENTS.md — AuditKit Brief

> Generated by [AuditKit](https://github.com/nirholas/AuditKit) on ${date}
> Target: \`${result.url}\`

## Overview

This brief was auto-generated from a full-stack audit of \`${result.url}\`. It contains all detected issues and exact fix instructions for an AI coding agent to resolve.

## Audit Scores

| Pillar | Score | Issues |
|--------|-------|--------|
${pillarSummary}

## Critical Issues (fix first)

${critical.length === 0 ? '_No critical issues found. 🎉_' : issueList(critical)}

## Warnings

${warnings.length === 0 ? '_No warnings found._' : issueList(warnings)}

## Agent Instructions

You are a senior web developer tasked with resolving the issues listed above for \`${result.url}\`.

**Priority order:**
1. Fix all critical issues first — they affect crawlability, security, or Core Web Vitals
2. Resolve warnings — they affect SEO ranking and user experience
3. Implement missing AI readiness files (AGENTS.md, llms.txt, CLAUDE.md) if not present

**Constraints:**
- Do not change the site's design or content unless fixing a specific issue
- Test each fix before moving to the next
- For security headers, add them at the infrastructure level (server config, CDN, Next.js headers)

**Deliverables:**
- A PR or commit for each pillar group of fixes
- Updated scores should show improvement of ≥15 points across all affected pillars
`
}

// ─── CLAUDE.md ────────────────────────────────────────────────────────────────

export function generateClaudeMd(result: AuditResult): string {
    const allIssues = result.pillars.flatMap((p) => p.issues)
    const criticalIds = allIssues.filter((i) => i.severity === 'critical').map((i) => i.id)

    return `# CLAUDE.md — AuditKit Fix Brief

Guidelines for Claude Code when resolving AuditKit findings for \`${result.url}\`.

## Critical Issue IDs to Fix First

${criticalIds.length > 0 ? criticalIds.map((id: string) => `- \`${id}\``).join('\n') : '_None — all clear!_'}

## Commands

After making changes, verify with:
\`\`\`bash
# Re-run PageSpeed
curl "https://www.googleapis.com/pagespeedonline/v5/runPagespeed?url=${result.url}&strategy=mobile"

# Check security headers
curl -I "${result.url}"

# Validate structured data
# Visit: https://search.google.com/test/rich-results?url=${encodeURIComponent(result.url)}
\`\`\`

## Important

- Security headers must be set at the server/CDN level, not in HTML meta tags
- For Next.js: add headers in \`next.config.ts\` under the \`headers()\` export
- For performance: run Lighthouse before and after each change to confirm improvement
- Do not modify content, only technical implementation
- After 2 failed fix attempts on the same issue, stop and report back

## Audit Source

Full results available in \`AGENTS.md\` in this directory.
`
}

// ─── GEMINI.md ────────────────────────────────────────────────────────────────

export function generateGeminiMd(result: AuditResult): string {
    return `# GEMINI.md — AuditKit Fix Brief

Guidelines for Gemini when resolving AuditKit findings for \`${result.url}\`.

## Task

Resolve the issues listed in \`AGENTS.md\` for \`${result.url}\`. Focus on technical fixes only — do not modify content or design.

## Pillar Scores

${result.pillars.map((p) => `- **${p.label}**: ${p.score}/100 (${p.issues.length} issues)`).join('\n')}

## Process

1. Read AGENTS.md fully before starting
2. Fix issues pillar by pillar, starting with Security and Performance
3. Verify each fix with the validation commands in CLAUDE.md
4. Commit each pillar as a separate changeset

## Resources

- Google Search Console: https://search.google.com/search-console
- PageSpeed Insights: https://pagespeed.web.dev/?url=${encodeURIComponent(result.url)}
- Rich Results Test: https://search.google.com/test/rich-results?url=${encodeURIComponent(result.url)}
- Mozilla Observatory: https://observatory.mozilla.org/analyze/${new URL(result.url).hostname}
`
}

// ─── Skill file ───────────────────────────────────────────────────────────────

export function generateSkillMd(title: string, issues: AuditIssue[], url: string): string {
    return `# SKILL.md — ${title}

> Auto-generated by AuditKit for \`${url}\`

## Issues Found

${issues.map((i) => `### ${i.title}

**Severity:** ${i.severity}
**Description:** ${i.description}
${i.fix ? `**Fix:** ${i.fix}` : ''}
${i.snippet ? `\n\`\`\`\n${i.snippet}\n\`\`\`` : ''}
${i.docs ? `**Docs:** ${i.docs}` : ''}
`).join('\n')}

## Verification

After applying fixes, re-run the audit at [AuditKit](https://github.com/nirholas/AuditKit) to confirm improvement.
`
}

// ─── robots.txt ───────────────────────────────────────────────────────────────

export function generateRobotsTxt(url: string): string {
    const origin = new URL(url).origin
    return `# robots.txt generated by AuditKit
# https://github.com/nirholas/AuditKit

User-agent: *
Allow: /

# AI crawlers — allow indexing (edit to restrict)
User-agent: GPTBot
Allow: /

User-agent: Claude-Web
Allow: /

User-agent: Google-Extended
Allow: /

User-agent: PerplexityBot
Allow: /

# Sitemap
Sitemap: ${origin}/sitemap.xml
`
}

// ─── Security headers (Next.js) ──────────────────────────────────────────────

export function generateSecurityHeaders(): string {
    return `// Security headers for next.config.ts
// Generated by AuditKit — https://github.com/nirholas/AuditKit

const securityHeaders = [
  {
    key: 'X-DNS-Prefetch-Control',
    value: 'on',
  },
  {
    key: 'Strict-Transport-Security',
    value: 'max-age=63072000; includeSubDomains; preload',
  },
  {
    key: 'X-Frame-Options',
    value: 'SAMEORIGIN',
  },
  {
    key: 'X-Content-Type-Options',
    value: 'nosniff',
  },
  {
    key: 'Referrer-Policy',
    value: 'strict-origin-when-cross-origin',
  },
  {
    key: 'Permissions-Policy',
    value: 'camera=(), microphone=(), geolocation=()',
  },
  // Uncomment and customise when ready:
  // {
  //   key: 'Content-Security-Policy',
  //   value: "default-src 'self'; script-src 'self' 'unsafe-eval' 'unsafe-inline'; ...",
  // },
]

// Add to your nextConfig:
// async headers() {
//   return [{ source: '/(.*)', headers: securityHeaders }]
// }

module.exports = securityHeaders
`
}

// ─── llms.txt template ────────────────────────────────────────────────────────

export function generateLlmsTxt(result: AuditResult): string {
    const hostname = new URL(result.url).hostname
    return `# ${hostname}

> This is the llms.txt file for ${hostname}, following the llms.txt standard.
> Learn more: https://llmstxt.org/

## About

[Add a 1-2 sentence description of your site/product here]

## Documentation

- [Homepage](${result.url})
- [Sitemap](${new URL(result.url).origin}/sitemap.xml)

## Key Pages

[List your most important pages here with descriptions]

## Contact

[Add contact or support information here]

---
*Generated by [AuditKit](https://github.com/nirholas/AuditKit)*
`
}
